### ISSUE TITLE
Update to core 7.50

### ISSUE THREAD

**Issue by vistar** [pressflow/7#66]
https://www.drupal.org/project/drupal/releases/7.50

**Comment by chrisgross** [comment]
any progress on this?

**Comment by kienanstewart** [comment]
I made this diff file by merging 7.50 into pressflow-7.44. Works on the surface - I didn't do any extensive testing. https://www.drupal.org/files/issues/pressflow-7.44_7.50.diff.

I applied to builds by adding the patch to core in my drush make files.

**Comment by AlexandrPoddubsky** [comment]
pressflow / 7 die ?

**Comment by fluxsauce** [comment]
@AlexandrPoddubsky no, an oversight. We'll take care of it shortly.

**Comment by fluxsauce** [comment]
Sorry about the delay, it's available now. https://github.com/pressflow/7/releases/tag/pressflow-7.50
