### ISSUE TITLE
Pressflow 7.78 Release

### ISSUE THREAD

**Issue by shaneonabike** [pressflow/7#96]
Hey there,

I see that you merged in the latest Drupal release security fixes but was wondering if you could also spin off a new release?

THANKS!

**Comment by vantagepointmedia** [comment]
This ^ Thank you

**Comment by emanuk** [comment]
+1

**Comment by macburgee1** [comment]
+1 for a 7.78 release

**Comment by generalredneck** [comment]
I got one in for 7.80. Sorry about the wait. In the future... totally feel free to ping me on the issue :) hope this helps!
